require 'default.rb'
require 'defaultMappingRegistry.rb'
require 'soap/rpc/driver'

class MantisConnectPortType < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "http://localhost/mantisbt/api/soap/mantisconnect.php"
  NsMantisconnect = "http://futureware.biz/mantisconnect"

  Methods = [
    [ XSD::QName.new(NsMantisconnect, "mc_version"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_version",
      "mc_version",
      [ ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_login"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_login",
      "mc_login",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["UserData", "http://futureware.biz/mantisconnect", "UserData"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_enum_status"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_enum_status",
      "mc_enum_status",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["ObjectRefArray", "http://futureware.biz/mantisconnect", "ObjectRefArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_enum_priorities"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_enum_priorities",
      "mc_enum_priorities",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["ObjectRefArray", "http://futureware.biz/mantisconnect", "ObjectRefArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_enum_severities"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_enum_severities",
      "mc_enum_severities",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["ObjectRefArray", "http://futureware.biz/mantisconnect", "ObjectRefArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_enum_reproducibilities"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_enum_reproducibilities",
      "mc_enum_reproducibilities",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["ObjectRefArray", "http://futureware.biz/mantisconnect", "ObjectRefArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_enum_projections"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_enum_projections",
      "mc_enum_projections",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["ObjectRefArray", "http://futureware.biz/mantisconnect", "ObjectRefArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_enum_etas"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_enum_etas",
      "mc_enum_etas",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["ObjectRefArray", "http://futureware.biz/mantisconnect", "ObjectRefArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_enum_resolutions"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_enum_resolutions",
      "mc_enum_resolutions",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["ObjectRefArray", "http://futureware.biz/mantisconnect", "ObjectRefArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_enum_access_levels"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_enum_access_levels",
      "mc_enum_access_levels",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["ObjectRefArray", "http://futureware.biz/mantisconnect", "ObjectRefArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_enum_project_status"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_enum_project_status",
      "mc_enum_project_status",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["ObjectRefArray", "http://futureware.biz/mantisconnect", "ObjectRefArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_enum_project_view_states"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_enum_project_view_states",
      "mc_enum_project_view_states",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["ObjectRefArray", "http://futureware.biz/mantisconnect", "ObjectRefArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_enum_view_states"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_enum_view_states",
      "mc_enum_view_states",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["ObjectRefArray", "http://futureware.biz/mantisconnect", "ObjectRefArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_enum_custom_field_types"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_enum_custom_field_types",
      "mc_enum_custom_field_types",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["ObjectRefArray", "http://futureware.biz/mantisconnect", "ObjectRefArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_enum_get"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_enum_get",
      "mc_enum_get",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "enumeration", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_exists"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_exists",
      "mc_issue_exists",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issue_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_get"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_get",
      "mc_issue_get",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issue_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["IssueData", "http://futureware.biz/mantisconnect", "IssueData"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_get_biggest_id"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_get_biggest_id",
      "mc_issue_get_biggest_id",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_get_id_from_summary"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_get_id_from_summary",
      "mc_issue_get_id_from_summary",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "summary", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_add"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_add",
      "mc_issue_add",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issue", ["IssueData", "http://futureware.biz/mantisconnect", "IssueData"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_update"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_update",
      "mc_issue_update",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issueId", ["::SOAP::SOAPInteger"]],
        ["in", "issue", ["IssueData", "http://futureware.biz/mantisconnect", "IssueData"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_set_tags"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_set_tags",
      "mc_issue_set_tags",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issue_id", ["::SOAP::SOAPInteger"]],
        ["in", "tags", ["TagDataArray", "http://futureware.biz/mantisconnect", "TagDataArray"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_delete"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_delete",
      "mc_issue_delete",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issue_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_note_add"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_note_add",
      "mc_issue_note_add",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issue_id", ["::SOAP::SOAPInteger"]],
        ["in", "note", ["IssueNoteData", "http://futureware.biz/mantisconnect", "IssueNoteData"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_note_delete"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_note_delete",
      "mc_issue_note_delete",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issue_note_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_note_update"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_note_update",
      "mc_issue_note_update",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "note", ["IssueNoteData", "http://futureware.biz/mantisconnect", "IssueNoteData"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_relationship_add"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_relationship_add",
      "mc_issue_relationship_add",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issue_id", ["::SOAP::SOAPInteger"]],
        ["in", "relationship", ["RelationshipData", "http://futureware.biz/mantisconnect", "RelationshipData"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_relationship_delete"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_relationship_delete",
      "mc_issue_relationship_delete",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issue_id", ["::SOAP::SOAPInteger"]],
        ["in", "relationship_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_attachment_add"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_attachment_add",
      "mc_issue_attachment_add",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issue_id", ["::SOAP::SOAPInteger"]],
        ["in", "name", ["::SOAP::SOAPString"]],
        ["in", "file_type", ["::SOAP::SOAPString"]],
        ["in", "content", ["::SOAP::SOAPBase64"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_attachment_delete"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_attachment_delete",
      "mc_issue_attachment_delete",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issue_attachment_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_attachment_get"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_attachment_get",
      "mc_issue_attachment_get",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issue_attachment_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["::SOAP::SOAPBase64"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_add"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_add",
      "mc_project_add",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project", ["ProjectData", "http://futureware.biz/mantisconnect", "ProjectData"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_delete"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_delete",
      "mc_project_delete",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_update"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_update",
      "mc_project_update",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["in", "project", ["ProjectData", "http://futureware.biz/mantisconnect", "ProjectData"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_get_id_from_name"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_get_id_from_name",
      "mc_project_get_id_from_name",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_name", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_get_issues"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_get_issues",
      "mc_project_get_issues",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["in", "page_number", ["::SOAP::SOAPInteger"]],
        ["in", "per_page", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["IssueDataArray", "http://futureware.biz/mantisconnect", "IssueDataArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_get_issue_headers"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_get_issue_headers",
      "mc_project_get_issue_headers",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["in", "page_number", ["::SOAP::SOAPInteger"]],
        ["in", "per_page", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["IssueHeaderDataArray", "http://futureware.biz/mantisconnect", "IssueHeaderDataArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_get_users"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_get_users",
      "mc_project_get_users",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["in", "access", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["AccountDataArray", "http://futureware.biz/mantisconnect", "AccountDataArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_projects_get_user_accessible"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_projects_get_user_accessible",
      "mc_projects_get_user_accessible",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["retval", "return", ["ProjectDataArray", "http://futureware.biz/mantisconnect", "ProjectDataArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_get_categories"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_get_categories",
      "mc_project_get_categories",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["StringArray", "http://futureware.biz/mantisconnect", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_add_category"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_add_category",
      "mc_project_add_category",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["in", "p_category_name", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_delete_category"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_delete_category",
      "mc_project_delete_category",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["in", "p_category_name", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_rename_category_by_name"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_rename_category_by_name",
      "mc_project_rename_category_by_name",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["in", "p_category_name", ["::SOAP::SOAPString"]],
        ["in", "p_category_name_new", ["::SOAP::SOAPString"]],
        ["in", "p_assigned_to", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_get_versions"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_get_versions",
      "mc_project_get_versions",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["ProjectVersionDataArray", "http://futureware.biz/mantisconnect", "ProjectVersionDataArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_version_add"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_version_add",
      "mc_project_version_add",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "version", ["ProjectVersionData", "http://futureware.biz/mantisconnect", "ProjectVersionData"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_version_update"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_version_update",
      "mc_project_version_update",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "version_id", ["::SOAP::SOAPInteger"]],
        ["in", "version", ["ProjectVersionData", "http://futureware.biz/mantisconnect", "ProjectVersionData"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_version_delete"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_version_delete",
      "mc_project_version_delete",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "version_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_get_released_versions"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_get_released_versions",
      "mc_project_get_released_versions",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["ProjectVersionDataArray", "http://futureware.biz/mantisconnect", "ProjectVersionDataArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_get_unreleased_versions"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_get_unreleased_versions",
      "mc_project_get_unreleased_versions",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["ProjectVersionDataArray", "http://futureware.biz/mantisconnect", "ProjectVersionDataArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_get_attachments"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_get_attachments",
      "mc_project_get_attachments",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["ProjectAttachmentDataArray", "http://futureware.biz/mantisconnect", "ProjectAttachmentDataArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_get_custom_fields"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_get_custom_fields",
      "mc_project_get_custom_fields",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["CustomFieldDefinitionDataArray", "http://futureware.biz/mantisconnect", "CustomFieldDefinitionDataArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_attachment_get"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_attachment_get",
      "mc_project_attachment_get",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_attachment_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["::SOAP::SOAPBase64"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_attachment_add"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_attachment_add",
      "mc_project_attachment_add",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["in", "name", ["::SOAP::SOAPString"]],
        ["in", "title", ["::SOAP::SOAPString"]],
        ["in", "description", ["::SOAP::SOAPString"]],
        ["in", "file_type", ["::SOAP::SOAPString"]],
        ["in", "content", ["::SOAP::SOAPBase64"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_attachment_delete"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_attachment_delete",
      "mc_project_attachment_delete",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_attachment_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_project_get_all_subprojects"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_project_get_all_subprojects",
      "mc_project_get_all_subprojects",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["StringArray", "http://futureware.biz/mantisconnect", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_filter_get"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_filter_get",
      "mc_filter_get",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["FilterDataArray", "http://futureware.biz/mantisconnect", "FilterDataArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_filter_get_issues"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_filter_get_issues",
      "mc_filter_get_issues",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["in", "filter_id", ["::SOAP::SOAPInteger"]],
        ["in", "page_number", ["::SOAP::SOAPInteger"]],
        ["in", "per_page", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["IssueDataArray", "http://futureware.biz/mantisconnect", "IssueDataArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_filter_get_issue_headers"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_filter_get_issue_headers",
      "mc_filter_get_issue_headers",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["in", "filter_id", ["::SOAP::SOAPInteger"]],
        ["in", "page_number", ["::SOAP::SOAPInteger"]],
        ["in", "per_page", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["IssueHeaderDataArray", "http://futureware.biz/mantisconnect", "IssueHeaderDataArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_config_get_string"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_config_get_string",
      "mc_config_get_string",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "config_var", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_issue_checkin"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_issue_checkin",
      "mc_issue_checkin",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "issue_id", ["::SOAP::SOAPInteger"]],
        ["in", "comment", ["::SOAP::SOAPString"]],
        ["in", "fixed", ["::SOAP::SOAPBoolean"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_user_pref_get_pref"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_user_pref_get_pref",
      "mc_user_pref_get_pref",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "project_id", ["::SOAP::SOAPInteger"]],
        ["in", "pref_name", ["::SOAP::SOAPString"]],
        ["retval", "return", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_user_profiles_get_all"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_user_profiles_get_all",
      "mc_user_profiles_get_all",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "page_number", ["::SOAP::SOAPInteger"]],
        ["in", "per_page", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["ProfileDataSearchResult", "http://futureware.biz/mantisconnect", "ProfileDataSearchResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_tag_get_all"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_tag_get_all",
      "mc_tag_get_all",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "page_number", ["::SOAP::SOAPInteger"]],
        ["in", "per_page", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["TagDataSearchResult", "http://futureware.biz/mantisconnect", "TagDataSearchResult"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_tag_add"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_tag_add",
      "mc_tag_add",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "tag", ["TagData", "http://futureware.biz/mantisconnect", "TagData"]],
        ["retval", "return", ["::SOAP::SOAPInteger"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsMantisconnect, "mc_tag_delete"),
      "http://localhost/mantisbt/api/soap/mantisconnect.php/mc_tag_delete",
      "mc_tag_delete",
      [ ["in", "username", ["::SOAP::SOAPString"]],
        ["in", "password", ["::SOAP::SOAPString"]],
        ["in", "tag_id", ["::SOAP::SOAPInteger"]],
        ["retval", "return", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = DefaultMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = DefaultMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

